INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (1, 1, 1, 2345, 3, 0, 2345);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (2, 1, 2, 5243, 2, 2, 5243);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (3, 1, 3, 23, 4, 4, 23);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (4, 1, 5, 67, 3,2, 67);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (5, 2, 6, 98, 1, 1, 98);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (6, 2, 7, 123, 2, 1, 123);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (7, 2, 8, 653, 10, 8, 653);

INSERT INTO PURCHASEORDERDETAILS (DETAILSID, ORDERID, PRODUCT, COST, ORDERQTY, RECEIVEDQTY, TOTAL) 
VALUES (8, 3, 9, 234, 7, 4, 234);