INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (1

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (2

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (3

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (4

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (5

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (6

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (7

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (8

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (9

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (10

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (11

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (12

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (13

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (14

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (15

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (16

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (17

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (18

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (19

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (20

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (21

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (22

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (23

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (24

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (25

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (26

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (27

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (28

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (29

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (30

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (31

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (32

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (33

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (34

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (35

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (36

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (37

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (38

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (39

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (40

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (41

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (42

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (43

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (44

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (45

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (46

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (47

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (48

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (49

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (50

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (51

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (52

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (53

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (54

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (55

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (56

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (57

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (58

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (59

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (60

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (61

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (62

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (63

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (64

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (65

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (66

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (67

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (68

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (69

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (70

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (71

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (72

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (73

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (74

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (75

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (76

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (77

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (78

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (79

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (80

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (81

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (82

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (83

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (84

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (85

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (86

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (87

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (88

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (89

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (90

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (91

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (92

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (93

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (94

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (95

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (96

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (97

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (98

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (99

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (100

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (101

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (102

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (103

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (104

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (105

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (106

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (107

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (108

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (109

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (110

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (111

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (112

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (113

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (114

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (115

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (116

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (117

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (118

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (119

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (120

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (121

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (122

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (123

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (124

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (125

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (126

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (127

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (128

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (129

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (130

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (131

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (132

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (133

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (134

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (135

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (136

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (137

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (138

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (139

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (140

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (141

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (142

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (143

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (144

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (145

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (146

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (147

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (148

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (149

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (150

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (151

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (152

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (153

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (154

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (155

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (156

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (157

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (158

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (159

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (160

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (161

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (162

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (163

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (164

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (165

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (166

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (167

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (168

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (169

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (170

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (171

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (172

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (173

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (174

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (175

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (176

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (177

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (178

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (179

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (180

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (181

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (182

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (183

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (184

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (185

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (186

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (187

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (188

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (189

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (190

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (191

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (192

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (193

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (194

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (195

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (196

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (197

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (198

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (199

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (200

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (201

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (202

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (203

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (204

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (205

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (206

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (207

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (208

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (209

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (210

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (211

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (212

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (213

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (214

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (215

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (216

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (217

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (218

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (219

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (220

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (221

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (222

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (223

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (224

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (225

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (226

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (227

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (228

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (229

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (230

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (231

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (232

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (233

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (234

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (235

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (236

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (237

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (238

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (239

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (240

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (241

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (242

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (243

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (244

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (245

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (246

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (247

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (248

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (249

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (250

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (251

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (252

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (253

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (254

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (255

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (256

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (257

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (258

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (259

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (260

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (261

INSERT INTO PRODUCT (ID, CATEGORY_ID, DESCRIPTION, UNITMEASURE, PART_ID, MANUFACTURER, SUPPLIER, PRICE, STATUS, LASTCHANGE) 
VALUES (262