INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (1, 1, 8, sysdate(), 1, null, null, 456.32, 7.1, 546.76, 1, sysdate(), 1, "Issued", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (2, 2, 8, sysdate(), 2, null, null, 456.32, 7.1, 546.76, 1, sysdate(), 2, "Back Order", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (3, 3, 8, sysdate(), 3, null, null, 456.32, 7.1, 546.76, 1, sysdate(), 3, "Back Order", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (4, 4, 8, sysdate(), 4, null, null, 456.32, 7.1, 546.76, 2, sysdate(), 4, "Back Order", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (5, 5, 3, sysdate(), 5, null, null, 456.32, 7.1, 546.76, 2, sysdate(), 5, "Issued", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (6, 6, 3, sysdate(), 6, null, null, 456.32, 7.1, 546.76, 2, sysdate(), 6, "Pending", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (7, 7, 4, sysdate(), 7, null, null, 456.32, 7.1, 546.76, 3, sysdate(), 7, "Issued", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (8, 1, 6, sysdate(), 8, null, null, 456.32, 7.1, 546.76, 3, sysdate(), 8, "Pending", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (9, 2, 2, sysdate(), 9, null, null, 456.32, 7.1, 546.76, 3, sysdate(), 9, "Issued", 6.8, null);

INSERT INTO PURCHASEORDER (ORDERID, SUPPLIER, JOB, EXPECTEDBY, CONTACT, QUOTE, QUOTEDATE, SUBTOTAL, TAX, TOTAL, CREATEDBY, CREATED, SHIPTO, STATUS, CURRENTTAX, COMMENTS)
VALUES (10, 2, 13, sysdate(), 10, null, null, 456.32, 7.1, 546.76, 3, sysdate(), 10, "Pending", 6.8, null);